apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
